### ISSUE TITLE
Show correct icon in Dash

### ISSUE THREAD

**Issue by elpraga** [shafayetrahat/YouBoxPlayer#1]
Hey!
I really like this little app. There is one little annoying thing though. 

Once I launch the app, it gets this ugly generic missing icon icon in GNOME Dash. Also when I put the mouse over the icons I get __Youtubeui.py__ as the name, instead of the correct name.

Do you have any idea how to use the correct icon? I tried to do it myself, but I didn't figure it out.

I'm not talking about the `.desktop` file icon. I mean the icon that is shown in Dash once the app is launched.

Tomas

**Comment by elpraga** [comment]
I found an example [here](https://stackoverflow.com/questions/21796722/beginner-on-pyqt4-no-window-icon) how to use an icon with pyqt4, but I was unable to modify it to work with your code.

I know almost nothing about python :smile:

**Comment by shafayetrahat** [comment]
thanks elpraga, this sorry for the delay message. the fixing will come soon.

**Comment by elpraga** [comment]
I've got it!

**Comment by elpraga** [comment]
I think I got the fix correctly in https://github.com/shafayetrahat/YouBoxPlayer/pull/2, but an incorrect name still appears in the Dash.

Do you have any idea how to fix that?

**Comment by shafayetrahat** [comment]
can you be more specific?

**Comment by elpraga** [comment]
I'll open a separate issue; the problems seem to be unrelated, and this one (with the icon) should be fixed by the commit I suggested.
